/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExerciciosJava_CapGemini;


import java.util.*;
import ExerciciosJava_CapGemini.helpers.*;
import java.util.*;
import java.lang.*;
        
        
public class App {
    
    
    public static void exercise1(){
           
         String arg[] = ParametersHelper.PopulateParameters(); 
         System.out.print("resultado da soma: ");
         System.out.println(CalculaTudo.CalculateAll(arg, 1));
    } 

    public static void exercise2(){
        String arg[] = ParametersHelper.PopulateParameters();
        
        System.out.print("Valor da soma: ");
        System.out.println(CalculaTudo.CalculateAll(arg, 1));
        
        System.out.print("Valor da subtracao: ");
        System.out.println(CalculaTudo.CalculateAll(arg, 2));
        
        System.out.print("Valor da multiplicacao: ");
        System.out.println(CalculaTudo.CalculateAll(arg, 3));
        
        System.out.print("Valor da divisao: ");
        System.out.println(CalculaTudo.CalculateAll(arg, 4));
        
        System.out.print("Valor do resto: ");
        System.out.println(CalculaTudo.CalculateAll(arg, 5));
        
    }
    
 
    
    public static void exercise3(){
        String header1 = ("Digite a distância percorrida: ");
        String header2 = ("Digite o consumo total de combustível: ");
        
        String arg[] = ParametersHelper.floatPopulateParameters(header1, header2);
               
        System.out.print("Consumo medio igual a: ");
        System.out.print(CalculaTudo.CalculateAll(arg, 4));
        System.out.print("km/l");
         
    }
    
    public static void exercise4(){
        String answer[] = CalculateSalaryAndComission.CalculateSalaryComission();
        
        System.out.print("Vendedor: "+ answer[0]);
        System.out.print(" ganha " + answer[1] + " de salário fixo");
        System.out.print(" e " + answer[2] + " de salario total");
    }
    
    public static void exercise5(){
        String answer[] = StudentAverageGrade.AverageCalculator();
        System.out.println("Aluno: " + answer[0]);
        
        System.out.println("obteve media: " + answer[1]);
    }
    
    public static void exercise6(){
        String answer[] = ValueSwap.SwapStrVariables();
        System.out.print("Após a troca - Variavel A: " +answer[0]);
        System.out.println(" e Variavel B: " +answer[1]);
    }

    public static void exercise7(){
        System.out.print(CelsiusFahrenheitConverter1.CelsiusToFahrenheit());
    }
    
    public static void Eexercise8(){
        System.out.print("a fazer");
    }
    
    public static void exercise9(){
        System.out.println(InterestRate.InterestRateCalculator(0.7f));
    }
    
    public static void exercise10(){
        
        System.out.println(InterestRate.Parcelation());
    }
   
    public static void exercise11(){
        System.out.println(InterestRate.AddMargin());
    }
    
    public static void exercise12(){
        System.out.println("R$ " +InterestRate.AddMarginAndTaxes());
    }
    
    public static void exercise13(){
        
        System.out.println(numberComparison.underTen());
    }
    public static void exercise14(){
        System.out.println(numberComparison.integerCompare());
    }
    
    public static void exercise15(){
        System.out.println(numberComparison.betweenHundreds());
    }
    
    public static void exercise16(){
        String[] answer = StudentAverageGrade.AverageCalculator();
        
        float finalGrade = Float.parseFloat(answer[1]);
        System.out.println("Nota final " + String.format("%.2f", finalGrade));
        
        if( finalGrade >= 7.0f ){
            
            System.out.println(answer[0] + " Aprovado");
            return;
        } else if (finalGrade < 7.0f && finalGrade >= 5.1f){
            System.out.println(answer[0] + " em Recuperacao");
            return;
        } else if (finalGrade <= 5.0f){
            System.out.println(answer[0] + " Reprovado");
            return;
        }
    }
    
    public static void exercise17(){
        System.out.print("números dentro do interavlo");
        System.out.println(RandomNumberProvider.randomNumberArrayAndFilter(80, 10, 150, 160));
    }
    
    public static void exercise18(){
        for(PessoaClass pessoa: RandomNumberProvider.PeopleListGenerator(300, 18, 50)){
            System.out.println(pessoa.getName() + " " + pessoa.getMaioridade());
        }
        System.out.println();
    }
    
    public static void exercise19(){
        for(PessoaClass pessoa: RandomNumberProvider.PeopleListGenerator(56, 18, 80)){
            System.out.println(pessoa.getName() + " " + pessoa.getGender());
        }
        System.out.println();
    }
    
    public static void exercise20(){
        QuestionarioRecorrente.PerguntaRecorrenteCarro(8,"n");
    }
    
    public static void exercise21(){
        FiltroServicoMilitar.interfaceServicoMilitar();
    }
    
    public static void exercise22(){
        ProdutoClass.manageListProduto();
    }
    
    public static void exercise23(){
        
       int selector = NumberArgumentObject.allEvalNumber(40, 25, 80);
       
       if( selector == 1 ){
            exercise23();
            return;
        }
       
       if(selector == 2) { 
           System.out.println("numero igual a " + 40);
           return;
       }
       if(selector == 3) {
           System.out.println("numero menor que " + 25);
           return;
       }
       if(selector == 4) {
           System.out.println("numero maior que " + 80);
           return;
       }
       
       
       
    }
    
        public static void exercise24(){
            
        int times = NumberArgumentObject.askNumberReturnNumber().intValue();
        System.out.println("Times equals: " + times);
        
        List<Number> numberList = new ArrayList<>();
        
        numberList = NumberArgumentObject.askAnyNumbersReturnNumberList(times, numberList);
        for(Number evalNumber : numberList){
            
            int selector = NumberArgumentObject.allEvalNumberNoAsk(evalNumber, 0, 0, 0);
            
            if( selector == 1 ){
                //exercise24();
                System.out.println("error");
                //return;
            }
       
            if(selector == 2) { 
                System.out.println( evalNumber + " numero igual a " + 0);
                //return;
            }
            if(selector == 3) {
                System.out.println(evalNumber + " numero positivo");
                //return;
            }
            if(selector == 4) {
                System.out.println(evalNumber + " numero negativo" );
                //return;
            }
        }
    }
        
    public static void exercise25(){
        Number firstNumber = NumberArgumentObject.askNumberReturnNumber();
        Number secondNumber = NumberArgumentObject.askNumberReturnNumber();
        String answer = NumberArgumentObject.CompareTwoNumbers(firstNumber, secondNumber);
        
        System.out.println("Comparacao entre: " + firstNumber + " e " + secondNumber);
        System.out.println(answer);
    }
    
    
    public static void exercise26(){
        int digitNumber = NumberArgumentObject.askNumberReturnNumber().intValue();
        String answer = NumberArgumentObject.NumberExtense(digitNumber);
    }
    
    public static void exercise27(){
        
        
        List<CarroClass> carroList = new ArrayList<>();
        
        do{

            String escolhaUsuario = QuestionarioRecorrente.SistemaPerguntaRecorrente("Registrar Novo Carro?");
            if (escolhaUsuario.equalsIgnoreCase("Sim") || escolhaUsuario.equalsIgnoreCase("S")){
                CarroClass carro = new CarroClass();

                String strPrecoCarro = QuestionarioRecorrente.SistemaPerguntaRecorrente("Qual preco do carro novo?");          
                if(strPrecoCarro.equalsIgnoreCase("0")){
                    break;
                }
                carro.setOpcaoName("Carro");
                carro.setPrecoTabela(Float.parseFloat(strPrecoCarro));
                
                String strDescontoPorTipoCombustivel = QuestionarioRecorrente.SistemaPerguntaRecorrente("Qual tipo de Combustivel do carro?");
                carro.setDescontoTipoCombustivel(strDescontoPorTipoCombustivel);

                System.out.println(carro.getOpcaoName() + " - " + carro.getPrecoTabela() + " - " + carro.getDescontoReal());
                carroList.add(carro);
            } else if(escolhaUsuario.equalsIgnoreCase("Nao") || escolhaUsuario.equalsIgnoreCase("N")){
                break;
            }
        
        } while (true);
        
        System.out.println("Printing results:");
        
        
        for(CarroClass carro : carroList){
            System.out.println(carro.getOpcaoName() + " - " + carro.getPrecoTabela() + " - " + carro.getDescontoReal());
            System.out.println("Valor a ser pago pelo cliente: " + (carro.getPrecoTabela() *(1 - carro.getDescontoReal())));
        }
        
    }
    
    public static void main(String[] args) {

        new App().exercise27();
        
        System.out.println();
        //new App().Calculate();
        //System.out.println(new App().CalculateAll());
    }
}
